# FIXME: selectively include/exclude -- must not break technical usage esp. w/r/t laravel facades
matches:
#   - trigger: 'Quebec'
#     replace: 'Québec'
#     propagate_case: true
#     word: true

#   - trigger: 'angstrom'
#     replace: 'ångström'
#     propagate_case: true
#     word: true

#   - trigger: 'brulee'
#     replace: 'brûlée'
#     propagate_case: true
#     word: true

#   - trigger: "cafe'"
#     replace: 'café'
#     propagate_case: true
#     word: true

#   - trigger: 'chateau'
#     replace: 'château'
#     propagate_case: true
#     word: true

#   - trigger: 'cliche'
#     replace: 'cliché'
#     propagate_case: true
#     word: true

#   - trigger: 'creme'
#     replace: 'crème'
#     propagate_case: true
#     word: true

#   - trigger: 'crepe'
#     replace: 'crêpe'
#     propagate_case: true
#     word: true

#   - trigger: 'debacle'
#     replace: 'débâcle'
#     propagate_case: true
#     word: true

#   - trigger: 'debutante'
#     replace: 'débutante'
#     propagate_case: true
#     word: true

#   - trigger: 'detente'
#     replace: 'détente'
#     propagate_case: true
#     word: true

#   - trigger: 'divorcee'
#     replace: 'divorcée'
#     propagate_case: true
#     word: true

#   - trigger: 'doppelganger'
#     replace: 'doppelgänger'
#     propagate_case: true
#     word: true

#   - trigger: 'eclair'
#     replace: 'éclair'
#     propagate_case: true
#     word: true

#   - trigger: 'eclat'
#     replace: 'éclat'
#     propagate_case: true
#     word: true

#   - trigger: 'emigre'
#     replace: 'émigré'
#     propagate_case: true
#     word: true

#   - trigger: 'entree'
#     replace: 'entrée'
#     propagate_case: true
#     word: true

#   - trigger: 'epee'
#     replace: 'épée'
#     propagate_case: true
#     word: true

#   - trigger: "expose'"
#     replace: 'exposé'
#     propagate_case: true
#     word: true

#   - trigger: 'facade'
#     replace: 'façade'
#     propagate_case: true
#     word: true

#   - trigger: 'fete'
#     replace: 'fête'
#     propagate_case: true
#     word: true

#   - trigger: 'fiance'
#     replace: 'fiancé'
#     propagate_case: true
#     word: true

#   - trigger: 'flambe'
#     replace: 'flambé'
#     propagate_case: true
#     word: true

#   - trigger: 'francais'
#     replace: 'français'
#     propagate_case: true
#     word: true

#   - trigger: 'habitue'
#     replace: 'habitué'
#     propagate_case: true
#     word: true

#   - trigger: 'ingenue'
#     replace: 'ingénue'
#     propagate_case: true
#     word: true

#   - trigger: 'jalapeno'
#     replace: 'jalapeño'
#     propagate_case: true
#     word: true

#   - trigger: 'manana'
#     replace: 'mañana'
#     propagate_case: true
#     word: true

#   - trigger: 'matinee'
#     replace: 'matinée'
#     propagate_case: true
#     word: true

#   - trigger: 'melange'
#     replace: 'mélange'
#     propagate_case: true
#     word: true

#   - trigger: 'melee'
#     replace: 'mêlée'
#     propagate_case: true
#     word: true

#   - trigger: 'moire'
#     replace: 'moiré'
#     propagate_case: true
#     word: true

#   - trigger: 'naive'
#     replace: 'naïve'
#     propagate_case: true
#     word: true

#   - trigger: "nee'"
#     replace: 'née'
#     propagate_case: true
#     word: true

#   - trigger: "ole'"
#     replace: 'olé'
#     propagate_case: true
#     word: true

#   - trigger: 'protege'
#     replace: 'protégé'
#     propagate_case: true
#     word: true

#   - trigger: "resume'"
#     replace: 'résumé'
#     propagate_case: true
#     word: true

#   - trigger: "rose'"
#     replace: 'rosé'
#     propagate_case: true
#     word: true

#   - trigger: 'saute'
#     replace: 'sauté'
#     propagate_case: true
#     word: true

#   - trigger: 'seance'
#     replace: 'séance'
#     propagate_case: true
#     word: true

#   - trigger: 'senor'
#     replace: 'señor'
#     propagate_case: true
#     word: true

#   - trigger: 'smorgasbord'
#     replace: 'smörgåsbord'
#     propagate_case: true
#     word: true

#   - trigger: 'soiree'
#     replace: 'soirée'
#     propagate_case: true
#     word: true

#   - trigger: "souffle'"
#     replace: 'soufflé'
#     propagate_case: true
#     word: true

#   - trigger: 'soupcon'
#     replace: 'soupçon'
#     propagate_case: true
#     word: true

#   - trigger: "touche'"
#     replace: 'touché'
#     propagate_case: true
#     word: true

#   - trigger: 'voila'
#     replace: 'voilà'
#     propagate_case: true
#     word: true
