---
global_vars:
  - name: clip
    type: clipboard

matches:
  - trigger: "# <"
    replace: "# <{{clipped}}>"
    vars:
      - name: clipped
        type: shell
        depends_on: ["clip"]
        params:
          cmd: |
            echo "$ESPANSO_CLIP" \
            | grep '^https://' || [[ $? == 1 ]]


  - trigger: ';#spdx'
    replace: |-
      # SPDX-FileCopyrightText: {{year}} {{form.author}}
      # SPDX-License-Identifier: {{form.license}}
    vars:
      - name: form
        type: form
        params:
          layout: |
            author: [[author]]
            license: [[license]]
          fields:
            author:
              default: Chris Montgomery <chris@cdom.io>
            license:
              type: choice
              default: GPL-3.0-or-later
              values:
                - GPL-3.0-or-later
                - MIT
                - Apache-2.0
                - MPL-2.0
                - BSD-3-Clause
      - name: year
        type: date
        params:
          format: '%Y'
