matches:
  - trigger: 'phila'
    replace: 'philadelphia'
    word: true
    propagate_case: true

  # System Architecture Strings (Markdown)
  - trigger: '`aard'
    replace: '`aarch64-darwin`'
  - trigger: '`aarl'
    replace: '`aarch64-linux`'
  - trigger: '`x8d'
    replace: '`x86_64-darwin`'
  - trigger: '`x8l'
    replace: '`x86_64-linux`'
