"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[[--scope]]
--when.repositories = ["~/Projects/work/"]
[--scope.user]
email = "chrismont@temple.edu"
[--scope.git]
auto-local-bookmark = true
