image: nixos/unstable
environment:
  NIX_CONFIG: |
    experimental-features = nix-command flakes
    substituters = https://cache.nixos.org https://dotfield.cachix.org https://nix-community.cachix.org
    trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= macos-builder.cachix.org-1:HPWcq59/iyqQz6HEtlO/kjD/a7ril0+/XJc+SZ2LgpI= dotfield.cachix.org-1:b5H/ucY/9PDARWG9uWA87ZKWUBU+hnfF30amwiXiaNk= iosevka-xtal.cachix.org-1:5d7Is01fs3imwU9w5dom2PcSskJNwtJGbfjRxunuOcw= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
secrets:
  - 58e36a99-0912-48b7-b08d-c042ff298e46
tasks:
  - check: |
      cd dotfield
      nix flake show --show-trace --print-build-logs --accept-flake-config
      nix flake check --show-trace --print-build-logs --accept-flake-config
