keys:
  - &cdom_age age15yyjuhudx0qaxrgshap4uwylvc6gek5dev7wsvc0zn32v6easp4qmyffmg
  # FIXME: add gpg! prob needs the sops-nix shell integration though...
  # &cdom_gpg 64604147C434F65EC306A21F135EEDD0F71934F3

  - &boschic age1wes6w27jntng7t0fl2scuz8l0s556e4m3x3q8qfczgah90kyfs3shuqvvl
  - &hodgepodge age1saydygdkg49p6g34ylds3m666x0nsr2f8clwcggsn9essqdkfqjsq9a25w
  - &ryosuke age1s2wwls2ltcjqsrlsrh4sn7q5u7xkdu6q7dtr3mk8z9mqmfh0kyvs5qx3ax
  - &tsone age1rza57uagvpnmsu6kras64ajpl48f3wcugyydvvf3g5acj0mulyasw4u665

# Creation rules are evaluated sequentially. The first match wins.
# https://github.com/mozilla/sops#using-sops-yaml-conf-to-select-kms-pgp-for-new-files
creation_rules:

  - path_regex: nixos/machines/boschic/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *boschic
  - path_regex: nixos/machines/hodgepodge/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *hodgepodge
  - path_regex: nixos/machines/ryosuke/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          # TODO: remove when ryosuke is stable
          - *boschic
          - *ryosuke
  - path_regex: nixos/machines/tsone/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *tsone

  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *boschic
          - *hodgepodge
          - *ryosuke
          - *tsone

## Reference:
# https://github.com/Mic92/sops-nix
# https://github.com/mozilla/sops
