---
keys:
  - &cdom_age age15yyjuhudx0qaxrgshap4uwylvc6gek5dev7wsvc0zn32v6easp4qmyffmg
  # FIXME: add gpg! prob needs the sops-nix shell integration though...
  # &cdom_gpg 64604147C434F65EC306A21F135EEDD0F71934F3

  - &cdom_at_tuvix age18yqe2svh9ck0san5uzthh6m774r2450hhz4ustguza2l8nttk30qxvtpf4

  - &boschic age1wes6w27jntng7t0fl2scuz8l0s556e4m3x3q8qfczgah90kyfs3shuqvvl
  - &hierophant age1nl8de4w4vlke0nls38jykhlygf3aenr6prkvu6ap5m9a6pd80q8sr9sk00
  - &hodgepodge age1saydygdkg49p6g34ylds3m666x0nsr2f8clwcggsn9essqdkfqjsq9a25w
  - &ryosuke age14rlwkyskyfz65vrvu2n4v3vslqvuqc8uk7vjsre9n52zpnhke30svsjvak

# Creation rules are evaluated sequentially. The first match wins.
# https://github.com/mozilla/sops#using-sops-yaml-conf-to-select-kms-pgp-for-new-files
creation_rules:
  ##: nixos machines
  - path_regex: nixos/machines/boschic/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *boschic
  - path_regex: nixos/machines/hierophant/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *hierophant
  - path_regex: nixos/machines/hodgepodge/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *hodgepodge
  - path_regex: nixos/machines/ryosuke/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *ryosuke

  ##: darwin machines
  - path_regex: darwin/machines/tuvix/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *cdom_at_tuvix

  ##: global
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *cdom_at_tuvix
          - *boschic
          - *hierophant
          - *hodgepodge
          - *ryosuke
## Reference:
# https://github.com/Mic92/sops-nix
# https://github.com/mozilla/sops
