---
keys:
  ##: admin keys
  - &cdom_age age15yyjuhudx0qaxrgshap4uwylvc6gek5dev7wsvc0zn32v6easp4qmyffmg
  - &cdom_pgp 64604147C434F65EC306A21F135EEDD0F71934F3

  ##: linux machines
  - &boschic age1wes6w27jntng7t0fl2scuz8l0s556e4m3x3q8qfczgah90kyfs3shuqvvl
  - &hierophant age1nl8de4w4vlke0nls38jykhlygf3aenr6prkvu6ap5m9a6pd80q8sr9sk00
  - &hodgepodge age1saydygdkg49p6g34ylds3m666x0nsr2f8clwcggsn9essqdkfqjsq9a25w
  - &ryosuke age14rlwkyskyfz65vrvu2n4v3vslqvuqc8uk7vjsre9n52zpnhke30svsjvak

  ##: workstation users
  - &cdom_at_tuvix age18yqe2svh9ck0san5uzthh6m774r2450hhz4ustguza2l8nttk30qxvtpf4

# NOTE: Each rule should have only *one* key group!
#       Key groups, which use the Shamir's Secret Sharing algorithm,
#                   are a feature used to increase the security of a secret
#                   by requiring *multiple* keys in order to decrypt a secret.
#       That is, the data will be _split_ across each group,
#       requiring consensus to decrypt.
#       Reference: <https://github.com/getsops/sops#214key-groups>
# NOTE: Creation rules are evaluated sequentially. The first match wins.
#       For this reason, it is important that creation rules are listed
#       from *most* to *least* specific.
#       <https://github.com/getsops/sops#using-sops-yaml-conf-to-select-kms-pgp-for-new-files>
creation_rules:
  - path_regex: boschic/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *boschic
        pgp:
          - *cdom_pgp

  - path_regex: hierophant/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *hierophant
        pgp:
          - *cdom_pgp

  - path_regex: hodgepodge/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *hodgepodge
        pgp:
          - *cdom_pgp

  - path_regex: ryosuke/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *ryosuke
        pgp:
          - *cdom_pgp

  - path_regex: tuvix/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *cdom_at_tuvix
        pgp:
          - *cdom_pgp

  ##: shared
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *cdom_age
          - *cdom_at_tuvix
          - *boschic
          - *hierophant
          - *hodgepodge
          - *ryosuke
        pgp:
          - *cdom_pgp

  # ##: ultimate
  # - age: *cdom_age
  #   pgp: *cdom_pgp
