#!/usr/bin/env bash

set -e

GITHUB_REPOSITORY="montchr/dots"
DOTFILES_ORIGIN="git@github.com:$GITHUB_REPOSITORY.git"
DOTFILES_BRANCH="feature/dotbot"
DOTFILES_TARBALL_URL="https://github.com/$GITHUB_REPOSITORY/tarball/${DOTFILES_BRANCH}"
DOTFILES_UTILS_URL="https://raw.githubusercontent.com/$GITHUB_REPOSITORY/${DOTFILES_BRANCH}/lib/utils.sh"
DOTFILES_DIR="${HOME}/.dots"

readonly GITHUB_REPOSITORY
readonly DOTFILES_ORIGIN
readonly DOTFILES_BRANCH
readonly DOTFILES_TARBALL_URL
readonly DOTFILES_UTILS_URL
readonly DOTFILES_DIR

SKIP_QUESTIONS=false


# ----------------------------------------------------------------------
# | Helper Functions                                                   |
# ----------------------------------------------------------------------

function download () {
  local url="$1"
  local output="$2"
  if command -v "curl" &>/dev/null; then
    curl -LsSo "$output" "$url" &>/dev/null
    return $?
  elif command -v "wget" &>/dev/null; then
    wget -qO "$output" "$url" &>/dev/null
    return $?
  fi
  return 1
}

# Download the dotfiles repo.
#
# Arguments:
#   Download method. Can be either `archive` or `git`.
function download_dotfiles () {
  local tmp_file=""

  print_in_purple "\n • Download and extract archive\n\n"
  tmp_file="$(mktemp /tmp/XXXXX)"
  download "$DOTFILES_TARBALL_URL" "$tmp_file"
  print_result $? "Download archive" "true"
  printf "\n"

  if ! $SKIP_QUESTIONS; then
    ask_for_confirmation "Do you want to store the dotfiles in '$DOTFILES_DIR'?"
    if ! user_confirmed; then
      DOTFILES_DIR=""
      while [ -z "$DOTFILES_DIR" ]; do
        ask "Please specify another location for the dotfiles (path): "
        DOTFILES_DIR="$(get_answer)"
      done
    fi

    # Ensure the `dotfiles` directory is available
    while [ -e "$DOTFILES_DIR" ]; do
      ask_for_confirmation "'$DOTFILES_DIR' already exists, do you want to overwrite it?"
      if user_confirmed; then
        rm -rf "$DOTFILES_DIR"
        break
      else
        DOTFILES_DIR=""
        while [ -z "$DOTFILES_DIR" ]; do
          ask "Please specify another location for the dotfiles (path): "
          DOTFILES_DIR="$(get_answer)"
        done
      fi
    done

    printf "\n"
  else
    rm -rf "$DOTFILES_DIR" &>/dev/null
  fi

  mkdir -p "${DOTFILES_DIR}"
  print_result $? "Create '$DOTFILES_DIR'" "true"

  # Extract archive in the `dotfiles` directory.
  extract "$tmp_file" "$DOTFILES_DIR"
  print_result $? "Extract archive" "true"

  rm -rf "$tmp_file"
  print_result $? "Remove archive"

  cd "${DOTFILES_DIR}"
  print_result $? "cd ${DOTFILES_DIR}"
  return $?
}

function download_utils () {
  local tmp_file=""
  tmp_file="$(mktemp /tmp/XXXXX)"

  download "$DOTFILES_UTILS_URL" "$tmp_file" && {
    # shellcheck disable=SC1090
    . "$tmp_file" && rm -rf "$tmp_file"
  } && return 0

  return 1
}

function extract () {
  local archive="$1"
  local outputDir="$2"
  if command -v "tar" &>/dev/null; then
    tar -zxf "$archive" --strip-components 1 -C "$outputDir"
    return $?
  fi
  return 1
}

function verify_os () {
  declare -r MINIMUM_MACOS_VERSION="10.10"
  # @TODO handle debian!
  declare -r MINIMUM_UBUNTU_VERSION="20.04"

  local os_name
  local os_version
  os_name="$(get_os)"
  os_version="$(get_os_version)"

  # Check if the OS is macOS and it's above the required version.
  if [ "$os_name" == "macos" ]; then
    if is_supported_version "$os_version" "$MINIMUM_MACOS_VERSION"; then
      return 0
    else
      printf "Sorry, this script is intended only for macOS %s+" "$MINIMUM_MACOS_VERSION"
    fi

    # Check if the OS is `Ubuntu` and it's above the required version.
  elif [ "$os_name" == "ubuntu" ]; then
    if is_supported_version "$os_version" "$MINIMUM_UBUNTU_VERSION"; then
      return 0
    else
      printf "Sorry, this script is intended only for Ubuntu %s+" "$MINIMUM_UBUNTU_VERSION"
    fi
  else
    printf "Sorry, this script is intended only for macOS and Ubuntu!"
  fi

  return 1
}

# Initialize dotfiles git repo in place.
# Globals:
#   DOTFILES_ORIGIN
function init_git_repo () {
  # @TODO set up branch tracking and submodules
  git init && git remote add origin "${DOTFILES_ORIGIN}"
}

# ----------------------------------------------------------------------
# | Main                                                               |
# ----------------------------------------------------------------------

function main () {
  # Ensure that the following actions are made relative to this file's path.
  cd "$(dirname "${BASH_SOURCE[0]}")" ||
    exit 1

  # Load utils
  if [[ -x "lib/utils.sh" ]]; then
    . "lib/utils.sh" || exit 1
  else
    download_utils || exit 1
  fi

  # Ensure the OS is supported and it's above the required version.
  verify_os ||
    exit 1

  # should_skip_questions "$@" &&
  #   SKIP_QUESTIONS=true

  if [[ "root" == $(whoami) ]]; then
    print_warning "Running as root! Dotfiles will be removed after creating sudo user."
  else
    ask_for_sudo
  fi

  print_hed "Downloading Dotfiles repo"
  download_dotfiles

  if [[ $DOTFILES_DIR != "$(pwd)" ]]; then
    print_error "We seem to be lost in '$(pwd)'. Something went wrong!"
    return 1
  fi

  print_hed "Install OS Essentials"
  . os/$(get_os)/install

  # @TODO add ubuntu configurator
  print_hed "Configure OS Preferences"
  if [[ -f os/$(get_os)/configure ]]; then
    ask "Set the system name: "
    . os/$(get_os)/configure "$(get_answer)"
  else
    print_warning "No configurator found for current OS '$(get_os)'! Continuing..."
  fi

  print_hed "Initializing Dotfiles"
  if [[ "root" == $(whoami) ]]; then
    print_in_purple "Removing dotfiles archive for root user..."
    cd "$HOME"
    rm -rf "${DOTFILES_DIR}"
  elif ! is_git_repository; then
    execute \
      init_git_repo \
      "Initialize the Git repository"
  fi

  if ! $SKIP_QUESTIONS; then
    print_hed "Restart"

    ask_for_confirmation "Do you want to restart? You probably should."
    printf "\n"

    if answer_is_yes; then
      sudo shutdown -r now &> /dev/null
    fi
  fi
}

main "$@"
