[global]
excludes = ["*generated*", "*secrets.yaml", "*secrets.yml"]

[formatter.js]
command = "sh"
includes = ["*.cjs", "*.js", "*.jsx", "*.mjs", "*.ts", "*.tsx"]
options = ["-eucx", """
    prettier --write "$@"
    eslint "$@"
  """, "--"]

[formatter.nix]
command = "sh"
excludes = ["home/modules/syncthing.nix"]
includes = ["*.nix"]
options = ["-eucx", """
    nixfmt "$@"
  """, "--"]

[formatter.prettier]
command = "prettier"
excludes = ["dark-reader.json", "devdocs.json", "karabiner.json"]
includes = [
  "*.css",
  "*.html",
  "*.json",
  "*.md",
  "*.mdx",
  "*.scss",
  "*.yaml",
  "*.yml",
]
options = ["--write"]

# [formatter.toml]
# command = "tomlfmt"
# includes = ["*toml"]
# options = ["--write"]

[formatter.shell]
command = "shfmt"
includes = ["*.sh", "*.bash"]
options = ["--simplify", "--write"]
