# https://github.com/numtide/treefmt/wiki

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]
excludes = [
  ##: upstreamable
  "home/modules/gpg-agent.nix",
  "home/modules/syncthing.nix",
  ##: generated files
  "packages/applications/firefox/firefox-addons/addons.nix",
  "packages/sources/_sources/*.nix",
]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
    "*.css",
    "*.html",
    "*.js",
    "*.json",
    "*.jsx",
    "*.md",
    "*.mdx",
    "*.scss",
    "*.ts",
    "*.tsx",
]
excludes = [
  "generated.json",
]

[formatter.shell]
command = "sh"
options = [
    "-eucx",
    """
##: 1) shellcheck
# FIXME: shellcheck may be too aggressive for now
# shellcheck --external-sources --source-path=SCRIPTDIR "$@"

##: 2) format
shfmt -i 2 -s -w "$@"
    """,
    "--", # bash swallows the second argument when using -c
]
includes = ["*.sh"]
excludes = []

[formatter.terraform]
# Terraform fmt only takes one file at the time so we create a wrapper.
# See https://github.com/numtide/treefmt/issues/97
command = "/bin/sh"
options = [
    "-euc",
    """
for f in "$@"; do
  terraform fmt "$f"
done
    """,
    "--",
]
includes = ["*.tf"]
