[global]
excludes = [
  "*.lock",
  "package-lock.json",
  ".gitignore",
  ".gitmodules",
  "npins/sources.json",
  "*secrets.yaml",
]
on-unmatched = "warn"

[formatter.actionlint]
command = "actionlint"
excludes = []
includes = [".github/workflows/*.yml", ".github/workflows/*.yaml"]
options = []

[formatter.biome]
command = "biome"
excludes = []
includes = [
  "*.js",
  "*.ts",
  "*.mjs",
  "*.mts",
  "*.cjs",
  "*.cts",
  "*.jsx",
  "*.tsx",
  "*.d.ts",
  "*.d.cts",
  "*.d.mts",
  "*.json",
  "*.jsonc",
  "*.css",
]
options = ["check", "--write", "--no-errors-on-unmatched"]

[formatter.kdlfmt]
command = "kdlfmt"
excludes = []
includes = ["*.kdl"]
options = ["format"]

[formatter.keep-sorted]
command = "keep-sorted"
excludes = []
includes = ["*"]
options = []

[formatter.mdformat]
command = "mdformat"
excludes = []
includes = ["*.md"]
options = []

[formatter.nixfmt-rfc-style]
command = "nixfmt"
excludes = []
includes = ["*.nix"]
options = []

[formatter.shfmt]
command = "shfmt"
excludes = []
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]
options = ["-s", "-w", "-i", "2"]

[formatter.taplo]
command = "taplo"
excludes = []
includes = ["*.toml"]
options = ["format"]

[formatter.yamlfmt]
command = "yamlfmt"
excludes = []
includes = ["*.yaml", "*.yml"]
# options = ["-conf=/nix/store/nv55sys1k1p6n9rzc9sr20nbsnq9mksz-yamlfmt.conf"]
