# espanso configuration file

matches:
  # Common
  - trigger: ":s.cmd"
    replace: "⌘"
  - trigger: ":s.shift"
    replace: "⇧"
  - trigger: ":s.ctrl"
    replace: "⌃"
  - trigger: ":s.shift"
    replace: "⌥"
  - trigger: ":s.esc"
    replace: "⎋"

  # Arrows :: :s.aa
  - trigger: ":s.aal"
    replace: "←"
  - trigger: ":s.aar"
    replace: "→"
  - trigger: ":s.aau"
    replace: "↑"
  - trigger: ":s.aad"
    replace: "↓"

  # Math
  - trigger: ":s.mult"
    replace: "×"
  - trigger: ":s.null"
    replace: "∅"
