#!/usr/bin/env bash
#
# os/ubuntu/install
#

set -e

# shellcheck source=../../lib/utils.sh
. "${DOTFILES_DIR}/lib/utils.sh"
# shellcheck source=./lib/pkg.sh
. "${DOTFILES_DIR}/os/ubuntu/lib/pkg.sh"


# - - - - - - - - - - - - - - - - - - - -
# Time
# - - - - - - - - - - - - - - - - - - - -

# Setup timezone.
function .setup_timezone () {
  local timezone

  ask "Enter the timezone for the server (Default is 'America/New_York')"
  timezone=$(get_answer)
  timezone=${timezone:-America/New_York}

  # Set the timezone.
  echo "${timezone}" | sudo tee /etc/timezone
  sudo ln -fs \
    "/usr/share/zoneinfo/${timezone}" \
    /etc/localtime # https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1554806
  sudo dpkg-reconfigure -f noninteractive tzdata

  print_in_yellow "Timezone is set to $(cat /etc/timezone)" >&3
}

function .setup_ntp () {
  ubuntu_version="$(lsb_release -sr)"

  if [[ $ubuntu_version == '20.04' ]]; then
    sudo systemctl restart systemd-timesyncd
  else
    sudo apt-get update
    sudo apt-get --assume-yes install ntp
  fi
}


# - - - - - - - - - - - - - - - - - - - -
# Cleanup
# - - - - - - - - - - - - - - - - - - - -

function .cleanup () {
  sudo service ssh restart

  [[ -f "/etc/sudoers.bak" ]] && {
    print_in_purple "Restoring original /etc/sudoers file..."
    sudo mv /etc/sudoers.bak /etc/sudoers
  }
}


# - - - - - - - - - - - - - - - - - - - -
# Main
# - - - - - - - - - - - - - - - - - - - -

function main () {

  pkg::update_repos
  pkg::upgrade_all

  pkg::install "Build Essential" "build-essential"
  pkg::install "GnuPG archive keys" "debian-archive-keyring"
  pkg::install "Git" "git"
  pkg::install "curl" "curl"

  if [[ "root" != $(whoami) ]]; then
    print_warning "Running as root! Creating a new user with sudo capabilities..."
    . ./user.sh
  fi

  execute \
    "sudo ufw allow OpenSSH; yes y | sudo ufw enable" \
    "Configure UFW"

  # Create and configure swapfile if it doesn't yet exist.
  [[ "$(sudo swapon -s)" != *"/swapfile"* ]] && {
    print_subhed "Swapfile doesn't exist! Creating and configuring swapfile..."
    . ./swapfile.sh
  }

  print_subhed "Configuring timezone..."
  .setup_timezone

  print_subhed "Installing/configuring Network Time Protocol..."
  .setup_ntp

  print_subhed "Cleaning up..."
  .cleanup

  print_success "Setup complete!"
}

main "$@"
