[
  ./profiles/core/default.nix
  ./profiles/atuin.nix
  ./profiles/development/nix-tools.nix
  ./profiles/direnv.nix
  ./profiles/fzf.nix
  ./profiles/git/default.nix
  ./profiles/helix.nix
  ./profiles/navi.nix
  ./profiles/nnn.nix
  ./profiles/nvim/default.nix
  ./profiles/rclone.nix
  ./profiles/shells/zsh/default.nix
  ./profiles/shells/zsh/with-grml.nix
  ./profiles/ssh.nix
  ./profiles/zellij.nix
  ./profiles/zoxide.nix
]
