---
matches:
  - replace: —
    trigger: :--.
  - replace: –
    trigger: :-.
  - replace: …
    trigger: :...
  - replace: «
    trigger: :<<
  - replace: »
    trigger: :>>
  - replace: ‘
    trigger: :'<
  - replace: ’
    trigger: :'>
  - replace: “
    trigger: :"<
  - replace: ”
    trigger: :">
  - replace: №
    trigger: :no.
