---
matches:
  - propagate_case: true
    replace: philadelphia
    trigger: phila
    word: true
  - replace: '`aarch64-darwin`'
    trigger: '`aard'
  - replace: '`aarch64-linux`'
    trigger: '`aarl'
  - replace: '`x86_64-darwin`'
    trigger: '`x8d'
  - replace: '`x86_64-linux`'
    trigger: '`x8l'
  - replace: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
    trigger: :sha-AAA
