#!/usr/bin/env bash
#
# Provision :: macOS :: Install
#


# - - - - - - - - - - - - - - - - - - - -
# Main
# - - - - - - - - - - - - - - - - - - - -

function main () {
  local previous_directory
  previous_directory="$PWD"

  cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

  guard::install && {
    guard::domain "packages" "Install baseline dependencies" && {
      cd "$XDG_CONFIG_HOME" && {
        export HOMEBREW_BUNDLE_FILE="${XDG_CONFIG_HOME}/Brewfile.${KERNEL_NAME}.bundle"
        brew bundle
      }
    }
  }


  guard::upgrade && {
    guard::domain "packages" "Upgrade packages" && {
      brew update
      brew upgrade
    }
  }

  cd "${previous_directory}" || return
}

main "$@"
