#!/usr/bin/env bash
#
# Provision :: macOS :: Install
#


function main () {
  guard::install && {
    msg::domain "Packages" "Ensure Homebrew exists" && {
      shell::has brew || {
        msg::info "Installing brew"
        /bin/bash -c "printf \"\n\" | $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew update
      }
    }
  }

  guard::domain "packages" "Install baseline dependencies" && {
    export HOMEBREW_BUNDLE_FILE="${DOTFIELD}/provision/macos/Brewfile.${KERNEL_NAME}.bundle"
    brew bundle
  }

  guard::install && {
    # FIXME: allow zsh
    msg::subdomain "Allow Homebrew's Bash as login shell"
    local brew_bash_path
    brew_bash_path="$(brew --prefix)/bin/bash"

    # Add the path of the Bash version installed through Homebrew to the list
    # of allowed login shells in the `/etc/shells` file.
    if ! grep "${brew_bash_path}" < /etc/shells &> /dev/null; then
      printf '%s\n' "${brew_bash_path}" | sudo tee -a /etc/shells
    fi
  }

  guard::upgrade && {
    guard::domain "packages" "Upgrade packages" && {
      brew upgrade
    }
  }
}

main "$@"
