## === TSONE ===

[tsone]
network = "cubegarden"
keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILGu6JFX4J6H3NgeQyuvCA2z2xh01um119P+tz5ZPWwO root@tsone",
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXREGzvnOtPeSGlRz+Bktw5ls6qyLoKPiEvVOcdPTFUpb/0m3qjI5eNraLfdG4tQ081DRllIgTaQ41gwYxpWKQVmlEOSRjsWrG/XVtVmXpcGPkvGCqNGjgugLLeC+qhEC+BbruhMh5LVb5pDe3ATzJ4BftOK8P8AD4cu7n+oID/MxMm8ZjDJqGccSPhtteHKTot29ofhL2Ra9CYgitQEHHO3/+nl+8C0jErNFINveAeidgDbtEsFYR93DPXQDp454Pqh9S3NdT4DbbwhhsMuVla3eFcFEb+WrjPcSrE6wf2MXYu1agL9Pic89uYMV4kypArAfJW6Su0uxWJkZWboKb71Yan/wwCekEtJyTcvL4443YPb8+gdpGSXAj41ZuWyebEHOyQ5XQNPfqgmQ+TjEb9extYif32HPu47MEoAxAtDOahsTiGABqc2CqBbzVCZfXea/bDBjMpuCfRENmsGDDRO72nqKk3Q+8g2nzkzueftkWggjxTkM1Q78TfN96EzP2WvcBqeaQlMDJSKrG/1WT5o9UENCJ0iAbWLyZ5pnryJSoU0hqEVsKvd6J1W8ljrgXRm5tIs/IAIASbE9QR6bnyCOa54dsfMogleQ3+a3JWk0yGBt/Sp0QKt7aQI/rh2RvzMrJtF4UWoQcVh2fdA8dgz2JgLdZlii57RyEg1wEAw== root@tsone"
]
age = "age1rza57uagvpnmsu6kras64ajpl48f3wcugyydvvf3g5acj0mulyasw4u665"

[tsone.ipv4]
address = "94.130.220.154"
prefixLength = 26
gateway = "94.130.220.129"

[tsone.ipv6]
addresses = [
  "2a01:4f8:13b:17ac::1",
]
# subnet = "2a01:4f8:13b:17ac::/64"
subnet = "2a01:4f8:13b:17ac"
prefixLength = 64
gateway = "fe80::1"

[tsone.users.cdom]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBzpSe7IG82Fl/djgmhclz1QPtduts0JOm9ZEOt075le cdom@tsone"]


## === HIEROPHANT ===
[hierophant]
network = "seadome"
keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP5ffhsQSZ3DsVddNzfsahN84SFnDWn9erSXiKbVioWy hierophant.loop.garden",
  # FIXME: add rsa key
]
age = "age1nl8de4w4vlke0nls38jykhlygf3aenr6prkvu6ap5m9a6pd80q8sr9sk00"

[hierophant.ipv4]
address = "100.68.129.15"

[hierophant.users.hierophant]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDwOUQFOaTPMtYG4VWrgHF772sf4MhmK5Rvq4vlUFFXH hierophant@loop.garden"]
age = "age18ngk35h7qycc9kzjc4fy788nvnvlce8gvjahkvkkjxlahd5r54vqhmq9y2"


## === RYOSUKE ===

[ryosuke]
network = "home"
tailscale = ""
keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIc3QGVaIcWs+IzEwRBB2Q6Hyejsj9nR4KENwzvzCVg4 root@ryosuke",
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQClKW9iYfEeRRGQgBKhERLP3ngOJOEwXtovHMcYAcO5wIjr0D05b8x01ICVYJgQblyoqVbeS70ykUEUkmlwsDM3056CIDgvvQIvDbMGOYCEx1deajRqDKXLcRzEuRSbSs8JuutdaQxtfcHq6HpiZ0NQVeUxgxmnQV0+d6LgA77TpuBFgJK8Nc7jA7fOD+4g0PEiVy3qO2SXVfo7DMpZVey3HSDdFmjM/TczswK9p+OqsL8F5PyE40ErqgOpdakRt/MTT+TWK0y2HgM6Oql+zJ7fY8bT561Cv2Qt7rcYtIYCZd+GOCoD0WdQ9om/8TzrxGOxg3xt4LOk3Czoa6BCNbqHAZdKmtgDfuDvGCzyaXAAQiKhahhv/D0rflGJpNQWJw4KcP2Lt19NSBf70Zgod1FX5PlcGZXof2VZrmRsEu4eEz0aNobwfW/OVILIY/d5N+d42FN4ZW0oqEwPv+ULgaUbil/afPiClf+YMIuyDp3tbbXCVy1p3R8oDwm5SnkgjOasQi5UkwSA3dXSHsiGJS+n17rVg39tLDz0Q8+JH71yZJLn3smN+2WT/uCYXXkkt6ws21AKiFRjL/OaQmpGBlJpzRn4cX7EamTKIsdoZdm6l1BeYE+4a6PQtAtVaKqoWi8YEB+7snWPGfOEFrT/dgXzv0MzDup5uTUy8QCbWcDSYQ== root@ryosuke",
]
age = "age1s2wwls2ltcjqsrlsrh4sn7q5u7xkdu6q7dtr3mk8z9mqmfh0kyvs5qx3ax"

[ryosuke.ipv4]
address = "192.168.1.217"

[ryosuke.users.cdom]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL+h4ovqnQQKAr9S4nMGJ4NmRq1klpC9APdDMRiHOI9d cdom@ryosuke"]
age = "age1fpjz2x5vlrtqr5hqy4mgmq6xf3uh3epalwek0shur574rm4hngks97taru"


## === BOSCHIC ===

[boschic]
network = "home"
tailscale = "100.112.94.38"
keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILieF9RIyF4rnqOyse7+3RMYQGH8IrBkTOuMb3O4oDXU root@boschic",
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC55brzXJiHpeY6ivYPshjG664jx87m7qLLv6ur8r5i9eWjQK9MIW4OB4Bfc4LKjNNSgeZ9Exs9L2V5ci3hFsBUUiANUuKNWrplO8CjHmAYndo1fQ+NlOqwTug+NOIjAjc4tZ2QxO1QLxBrRieF7UTBm52C4v3fIingi38UYGQje9JedFdxhuUWQW4a+VBpjYX7r6QjSd3+yO29u97fi9HxK54aVCW41ylsAOp75ty6HYoOi4cuqsZipFm+u4lTxj9XtEyernVX0dqIJLuKSB1WnZNeTe3U41+VeZG8H5eEiChJGbfWaAXRjYLiU15Akz/PVDXmkD19F7oqeqsU0VkaUi2y3vpADlMEi4jXaLsaX0xNkGvUyTLGr1TKBBlEDspr4ptN5EyvAzUFOwSAyEnsfjL9QaLs4kNgiJjzMYXr8w7CHfXgI7tw3ERryOS9FpfCo92KqHMkkQ8psqI/DOvxREY+uCeU4VPuiXLH2Q9w0TJuN3MC6V6cr3qiaMTZwaM6dLRb9FGHTk2XycP+EgJywM3zsc2MPijb4B9PXWlUIi20mnEQTVsGhiN738QwVTAWIlAPk4GnWcJLtrdRaOXUyEe/HAWks6vXeMAduKM1vF8MzgHKz4QJVsbcaPrOxAnS9i70UeA0qNjn3n9d2C9cATJEVS9OD2GoTbkMWWQ5uw== root@boschic",
]
age = "age1wes6w27jntng7t0fl2scuz8l0s556e4m3x3q8qfczgah90kyfs3shuqvvl"

[boschic.ipv4]
address = "192.168.1.214"

[boschic.users.seadoom]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICaZWAdHI5JfTzuXCNOTs8ebMjThMzhxS8uI28KB3uTx seadoom@boschic.loop.garden"]
age = "age1up0p4xs0lze04acxrlxqj374ymu0dfkmc6adz2psmlz8g57ddv2qvf6pd4"


## === HODGEPODGE ===

[hodgepodge]
network = "home"
tailscale = "100.71.240.35"
keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPRS3UkaJeMQm58v+ggR5e0hVeUbFZkhyQJwEC0LK5YS",
  # TODO: add rsa key
]
age = "age1saydygdkg49p6g34ylds3m666x0nsr2f8clwcggsn9essqdkfqjsq9a25w"

[hodgepodge.ipv4]
address = "192.168.1.174"

[hodgepodge.users.seadoom]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG+iDtB1+DXl89xmlHz6irAYfI2dm4ubinsH3apMeFeo seadoom@hodgepodge.loop.garden"]


## === SYNOXYN ===

[synoxyn]
network = "home"
# FIXME
# tailscale = ""

[synoxyn.ipv4]
address = "192.168.1.197"


## === AERATTUM ===

# note: on aerattum, an iphone, "users" are "apps"

[aerattum]
network = "seadome"

[aerattum.users.blink]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG2HrKDL60obU2mEkV1pM1xHQeTHc+czioQDTqu0gP37 blink@aerattum"]

[aerattum.users.workingcopy]
keys = ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrU4ZPmxcBNnMeLLyBkFcjlG2MwaIUp5deSycmXSb7gIC4MZKH0lvoCXsXBYTocGhwna2mg1SfpolLZzxzWAYpx52RoHeyY6ml/Z1dSJbpMgV5KZ2kqKo1hHar2i9wsc/EZQKv3rlngOSECiwg2LxHOIGGTz/779yEJnfnWnta+5Tnpk4zdgp8j8g+QbY7NFHcZg2mjcy++Nf2psqJsDZVE1JmzNsA30jEGaGDRAaAv9ZHcQf6E3GEpRvr3iqO9YTzOcgdzzl8CvAtZUa1G4piQK6CYkC6HgAvm73+kSm+JxssSfFi3xgK0+RLAUTGa25MH3PAqR9V8lrcuLI891sLEQTtQIIALfzTw04e740DqXRifzasCVo8lMmZBX8Mu+FC0KSFL0254OfHuTHDCWE7fc/3069pcpgAaJGIDj2rE3v631WqoPZpkmvefuu4+n5nvKe4ypwA/OH6h52s3CL7DlcREe6lnBraEzbuXxVL+0JP66yEzK4vFGtZWeTsbo9jyQkoJIw4IkuqHvRxElysOHaQqG08GkjiCBONiGIqk0GQ3pmeyjptfnrVyi2pFGTvVVQ06ZC7If3wywkWXCJzJ2nrD9B+gyRvKv557m24Goj2+LCi6IVZsFIh6r4+vOdaMnX39eol/kWMl1n93D8YG3bBS5JH0fEQsMZEpsUd7Q== WorkingCopy@aerattum"]


## === BRAKHAGE ===

[brakhage.users.blink]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEBWeCycDkYAqyXcgGOiy8cgnKDy8QL6F8lO+Jh7ZpLk blink@brakhage"]


## === INSTALLER: GRAPHICAL ===

[bootstrap-graphical]
network = "seadome"
