[buildPlans.iosevka-xtal]
family = "Iosevka Xtal"
spacing = "normal"
serifs = "sans"
no-cv-ss = false
# Required for Kitty. See Iosevka's custom build docs.
export-glyph-names = true

[buildPlans.iosevka-xtal.ligations]
inherits = "dlig"

[buildPlans.iosevka-xtal.variants.design]
capital-a = "curly-top-serifed"
capital-b = "standard-interrupted-unilateral-serifed"
capital-c = "serifless"
capital-d = "standard-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "descending-flat-hook-serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "hanging-motion-serifed"
capital-n = "motion-serifed"
capital-p = "open-motion-serifed"
capital-q = "open-swash"
capital-r = "standing-open-motion-serifed"
capital-s = "unilateral-inward-serifed"
capital-t = "serifless"
capital-u = "toothless-rounded"
capital-v = "straight"
capital-w = "straight-vertical-sides-motion-serifed"
capital-x = "curly-serifless"
capital-y = "straight-motion-serifed"
capital-z = "curly-bottom-serifed"
a = "double-storey-toothless-rounded"
b = "toothless-corner"
c = "serifless"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "extended"
g = "double-storey-open"
h = "straight"
i = "zshaped"
j = "flat-hook-serifed"
k = "symmetric-connected-serifless"
l = "hooky"
m = "earless-single-arch"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner"
r = "earless-corner"
t = "hookless-asymmetric"
u = "toothless-corner"
w = "straight-vertical-sides"
x = "curly-serifless"
y = "straight"
z = "straight-serifless"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-descending"
turn-v = "curly"
lower-iota = "tailed-serifed"
lower-lambda = "straight"
lower-mu = "tailed"
zero = "dotted"
one = "base-top-cut"
two = "straight-neck"
three = "flat-top"
four = "open-non-crossing"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "straight-crossbar"
eight = "crossing-asymmetric"
tilde = "low"
asterisk = "penta-high"
underscore = "high"
pilcrow = "low"
caret = "medium"
paren = "normal"
brace = "straight"
number-sign = "slanted-open"
ampersand = "closed"
at = "threefold"
dollar = "interrupted-cap"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
lig-ltgteq = "slanted"
question = "smooth"
punctuation-dot = "round"
