# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  firefox-lepton-ui = {
    pname = "firefox-lepton-ui";
    version = "97d8753ec2e816f4d00fd195d0a58894405f4546";
    src = fetchgit {
      url = "https://github.com/black7375/Firefox-UI-Fix";
      rev = "97d8753ec2e816f4d00fd195d0a58894405f4546";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-g2x4GokOCw4Me25tcJNPX9O0Cj+2TWhySxgAhzgAqOA=";
    };
  };
  fish-autopair = {
    pname = "fish-autopair";
    version = "1.0.4";
    src = fetchFromGitHub ({
      owner = "jorgebucaran";
      repo = "autopair.fish";
      rev = "1.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-s1o188TlwpUQEN3X5MxUlD/2CFCpEkWu83U9O+wg3VU=";
    });
  };
  fish-fifc = {
    pname = "fish-fifc";
    version = "adff5966739667d4c13d6388372e40f821571208";
    src = fetchgit {
      url = "https://github.com/gazorby/fifc";
      rev = "adff5966739667d4c13d6388372e40f821571208";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-tUhEfwVtcd1iSHsmkOzkB5B33qK+x/AZ56Dgs8QEaDk=";
    };
  };
  fish-replay = {
    pname = "fish-replay";
    version = "1.2.1";
    src = fetchFromGitHub ({
      owner = "jorgebucaran";
      repo = "replay.fish";
      rev = "1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-bM6+oAd/HXaVgpJMut8bwqO54Le33hwO9qet9paK1kY=";
    });
  };
  fzf-scripts = {
    pname = "fzf-scripts";
    version = "15156e3cb56c715464a2421e6f4e4356a26ac975";
    src = fetchgit {
      url = "https://github.com/DanielFGray/fzf-scripts";
      rev = "15156e3cb56c715464a2421e6f4e4356a26ac975";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-rynePmia169HOvL0M2GTWrndulS6dKjfx7rT0GK9J0I=";
    };
  };
  kitty-bortflower-icons = {
    pname = "kitty-bortflower-icons";
    version = "269c0f0bd1c792cebc7821f299ce9250ed9bcd67";
    src = fetchgit {
      url = "https://github.com/DinkDonk/kitty-icon.git";
      rev = "269c0f0bd1c792cebc7821f299ce9250ed9bcd67";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Vy+iLGnysrJMSLfkaYq15pb/wG4kIbfsXRrPgSc3OFs=";
    };
  };
  promnesia = {
    pname = "promnesia";
    version = "346b2e08e04604adffb17ae51244cd1b1ec9015f";
    src = fetchFromGitHub ({
      owner = "karlicoss";
      repo = "promnesia";
      rev = "346b2e08e04604adffb17ae51244cd1b1ec9015f";
      fetchSubmodules = false;
      sha256 = "sha256-GcLPJZQaHqPUGvcZMNlofwqTizh5/PywA4vY9N3Ih7s=";
    });
  };
  trellis-cli = {
    pname = "trellis-cli";
    version = "v1.8.0";
    src = fetchFromGitHub ({
      owner = "roots";
      repo = "trellis-cli";
      rev = "v1.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-w02vxf9PZDuHbrItKOYG1U7tUWnFMNKeJRjWa2FNz+c=";
    });
  };
}
