# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  cpanel-cli = {
    pname = "cpanel-cli";
    version = "76011d87384eeec6d81a15999d41e740db0dff95";
    src = fetchFromGitHub ({
      owner = "layfellow";
      repo = "cpanel-cli";
      rev = "76011d87384eeec6d81a15999d41e740db0dff95";
      fetchSubmodules = false;
      sha256 = "sha256-Dhow7cZ37pzR9REVubKiTHqrUHF78TI4Xy9EWUkpHkg=";
    });
  };
  firefox-lepton-ui = {
    pname = "firefox-lepton-ui";
    version = "fc204137f720b159e2102a7ace79bc9c3fba56af";
    src = fetchgit {
      url = "https://github.com/black7375/Firefox-UI-Fix";
      rev = "fc204137f720b159e2102a7ace79bc9c3fba56af";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-9BzKGD9CYm2g6tQjFnMrhO0zVLTKkUdjCXlriV8+b58=";
    };
  };
  fish-autopair = {
    pname = "fish-autopair";
    version = "1.0.4";
    src = fetchFromGitHub ({
      owner = "jorgebucaran";
      repo = "autopair.fish";
      rev = "1.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-s1o188TlwpUQEN3X5MxUlD/2CFCpEkWu83U9O+wg3VU=";
    });
  };
  fish-fifc = {
    pname = "fish-fifc";
    version = "adff5966739667d4c13d6388372e40f821571208";
    src = fetchgit {
      url = "https://github.com/gazorby/fifc";
      rev = "adff5966739667d4c13d6388372e40f821571208";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-tUhEfwVtcd1iSHsmkOzkB5B33qK+x/AZ56Dgs8QEaDk=";
    };
  };
  fish-replay = {
    pname = "fish-replay";
    version = "1.2.1";
    src = fetchFromGitHub ({
      owner = "jorgebucaran";
      repo = "replay.fish";
      rev = "1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-bM6+oAd/HXaVgpJMut8bwqO54Le33hwO9qet9paK1kY=";
    });
  };
  fzf-scripts = {
    pname = "fzf-scripts";
    version = "15156e3cb56c715464a2421e6f4e4356a26ac975";
    src = fetchgit {
      url = "https://github.com/DanielFGray/fzf-scripts";
      rev = "15156e3cb56c715464a2421e6f4e4356a26ac975";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-rynePmia169HOvL0M2GTWrndulS6dKjfx7rT0GK9J0I=";
    };
  };
  kitty-bortflower-icons = {
    pname = "kitty-bortflower-icons";
    version = "269c0f0bd1c792cebc7821f299ce9250ed9bcd67";
    src = fetchgit {
      url = "https://github.com/DinkDonk/kitty-icon.git";
      rev = "269c0f0bd1c792cebc7821f299ce9250ed9bcd67";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Vy+iLGnysrJMSLfkaYq15pb/wG4kIbfsXRrPgSc3OFs=";
    };
  };
  promnesia = {
    pname = "promnesia";
    version = "346b2e08e04604adffb17ae51244cd1b1ec9015f";
    src = fetchFromGitHub ({
      owner = "karlicoss";
      repo = "promnesia";
      rev = "346b2e08e04604adffb17ae51244cd1b1ec9015f";
      fetchSubmodules = false;
      sha256 = "sha256-GcLPJZQaHqPUGvcZMNlofwqTizh5/PywA4vY9N3Ih7s=";
    });
  };
  trellis-cli = {
    pname = "trellis-cli";
    version = "v1.7.0";
    src = fetchFromGitHub ({
      owner = "roots";
      repo = "trellis-cli";
      rev = "v1.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-/YUoGPVTbmegr8cmjhtHnG1jiwIjen91sUWjgK3T8GQ=";
    });
  };
}
