global_vars:
- name: clip
  type: clipboard
matches:
- replace: '# <{{clipped}}>'
  trigger: '# <'
  vars:
  - depends_on:
    - clip
    name: clipped
    params:
      cmd: 'echo "$ESPANSO_CLIP" \

        | grep ''^https://'' || [[ $? == 1 ]]

        '
    type: shell
- replace: ;; <{{clipped}}>
  trigger: ;; <
  vars:
  - depends_on:
    - clip
    name: clipped
    params:
      cmd: 'echo "$ESPANSO_CLIP" \

        | grep ''^https://'' || [[ $? == 1 ]]

        '
    type: shell
- replace: ''' :: <{{clipped}}>'
  trigger: ''' :: <'
  vars:
  - depends_on:
    - clip
    name: clipped
    params:
      cmd: 'echo "$ESPANSO_CLIP" \

        | grep ''^https://'' || [[ $? == 1 ]]

        '
    type: shell
- replace: '# SPDX-FileCopyrightText: (C) {{year}} {{form.author}}

    # SPDX-License-Identifier: {{form.license}}'
  trigger: ;#spdx
  vars:
  - name: form
    params:
      fields:
        author:
          default: Chris Montgomery <chmont@protonmail.com>
          type: choice
          values:
          - Chris Montgomery <chmont@protonmail.com>
          - Temple University <kleinweb@temple.edu>
        license:
          default: GPL-3.0-or-later
          type: choice
          values:
          - GPL-3.0-or-later
          - MIT
          - Apache-2.0
          - MPL-2.0
          - BSD-3-Clause
      layout: 'author: [[author]]

        license: [[license]]

        '
    type: form
  - name: year
    params:
      format: '%Y'
    type: date
