_: {
  # programs.mako = ...
  # programs.waybar = ...
  # services.cbatticon = ...
  # services.dunst = ...
  # services.kanshi = ...
  # services.network-manager-applet = ...
  # services.pasystray = ...
  # services.poweralertd = ...
  # services.swayidle = ...
  # services.systembus-notify = ...
  # services.volnoti = ...
  # wayland.windowManager.sway = ...
}
