#!/usr/bin/env bash
#
# Toggle system dark mode and run various related effects.
#
# Supports:
# - kitty
# - emacs

[[ -z $DOTFIELD_DIR ]] && {
  echo 'DOTFIELD_DIR not defined!' 1>&2
  return 1
}

# shellcheck source=../../../lib/utils.sh
. "${DOTFIELD_DIR}/lib/utils.sh"


function kitty::theme_change() {
  kitty @ --to unix:/tmp/kitty-socket \
    set-colors -a -c "${XDG_CONFIG_HOME}/kitty/themes/${appearance}.conf"
}

function emacs::theme_change () {
  emacsclient --no-wait --eval "(modus-themes-toggle)"
}

function main() {
  local appearance
  local theme
  # local base16_fzf_dir

  dark-mode || {
    msg::error "Could not switch system appearance mode!"
    exit 1
  }

  appearance="$(dotfield_os_appearance)"
  theme="$(dotfield_base16_theme "${appearance}")"
  kitty::theme_change "${appearance}"
  emacs::theme_change "${theme}"
}

main "$@"
