# wp-cli
complete -c wp -l cache --description 'Manage the object cache.'
complete -c wp -l cap --description 'Manage user capabilities.'
complete -c wp -l cli --description 'Get information about WP-CLI itself.'
complete -c wp -l comment --description 'Manage comments.'
complete -c wp -l core --description 'Download, install, update and otherwise manage WordPress proper.'
complete -c wp -l cron --description 'Manage WP-Cron events and schedules.'
complete -c wp -l db --description 'Perform basic database operations.'
complete -c wp -l eval --description 'Execute arbitrary PHP code.'
complete -c wp -l eval-file --description 'Load and execute a PHP file.'
complete -c wp -l export --description 'Export content to a WXR file.'
complete -c wp -l help --description 'Get help on WP-CLI, or on a specific command.'
complete -c wp -l import --description 'Import content from a WXR file.'
complete -c wp -l media --description 'Manage attachments.'
complete -c wp -l menu --description 'List, create, assign, and delete menus'
complete -c wp -l network --description ''
complete -c wp -l option --description 'Manage options.'
complete -c wp -l package --description 'Manage WP-CLI packages.'
complete -c wp -l plugin --description 'Manage plugins.'
complete -c wp -l post --description 'Manage posts.'
complete -c wp -l post-type --description 'Manage post types.'
complete -c wp -l rewrite --description 'Manage rewrite rules.'
complete -c wp -l role --description 'Manage user roles.'
complete -c wp -l scaffold --description 'Generate code for post types, taxonomies, etc.'
complete -c wp -l search-replace --description 'Search/replace strings in the database.'
complete -c wp -l server --description 'Launch PHPs built-in web server for this specific WordPress installation.'
complete -c wp -l shell --description 'Interactive PHP console.'
complete -c wp -l sidebar --description 'Manage sidebars.'
complete -c wp -l site --description 'Perform site-wide operations.'
complete -c wp -l super-admin --description 'List, add, and remove super admins from a network.'
complete -c wp -l taxonomy --description 'Manage taxonomies.'
complete -c wp -l term --description 'Manage terms.'
complete -c wp -l theme --description 'Manage themes.'
complete -c wp -l transient --description 'Manage transients.'
complete -c wp -l user --description 'Manage users.'
complete -c wp -l widget --description 'Manage sidebar widgets.'
