#!/usr/bin/env bash
#
# os/macos/install
#

# shellcheck source=../../vendor/bash-oo-framework/lib/oo-bootstrap.sh
source "${BASE_DIR}/vendor/bash-oo-framework/lib/oo-bootstrap.sh"


import \
  util/exception \
  util/tryCatch \
  util/namedParameters

import lib


function install_bash () {
  print_in_purple "Bash"

}


# - - - - - - - - - - - - - - - - - - - -
# Main
# - - - - - - - - - - - - - - - - - - - -

function main () {

  guard::domain "packages" "Ensure core CLI tools exist" && {
    xcode-select --install &> /dev/null
    execute "
        until $(xcode-select --print-path &> /dev/null); do \
          sleep 5; \
        done
      " "Xcode Command Line Tools"
  }

  guard::domain "packages" "Ensure brew exists" && {
    check brew || {
      msg::info "Installing brew"
      printf "\n" | \
        curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh &> /dev/null
      brew update
    }
  }


  guard::install && {

    guard::domain "packages" "Install all dependencies" && {
      cd "$target/macos" && brew bundle
    }

    guard::domain "packages" "Allow Homebrew's Bash as login shell" && {
      local brew_bash_path
      brew_bash_path="$(brew --prefix)/bin/bash"

      # Ensure we're using a recent version of Bash before anything else.
      brew install bash

      # Add the path of the Bash version installed through Homebrew to the list of
      # allowed login shells in the `/etc/shells` file.
      if ! grep "${brew_bash_path}" < /etc/shells &> /dev/null; then
        execute \
          "printf '%s\n' ${brew_bash_path} | sudo tee -a /etc/shells" \
          "Bash (add '${brew_bash_path}' in '/etc/shells')" \
            || return 1
      fi

      # Set Brew-installed version of Bash as the default (macOS comes with an
      # outdated version of Bash).
      chsh -s "${brew_bash_path}" &> /dev/null
      print_result $? "Bash (use latest version)"

    }

  }


  guard::upgrade && {
    guard::domain "packages" "Upgrade packages" && {
      brew update
      brew upgrade
    }
  }

}

main "$@"
