{ moduleWithSystem, ... }:
{
  dotfield.aspects.development.home = moduleWithSystem (
    perSystem@{ inputs', ... }:
    home@{ ... }:
    {
      nix.settings = {
        substituters = [ "https://tree-sitter-grammars.cachix.org" ];
        trusted-public-keys = [
          "tree-sitter-grammars.cachix.org-1:nOrtXe5HNC1EYPgHZDZ0GNgL02yFRkh2VrXNF0PW2iY="
        ];
      };
      nix.settings.trusted-substituters = [ "https://tree-sitter-grammars.cachix.org" ];

      home.packages = with inputs'.tree-sitter-grammars.packages; [
        tree-sitter-arduino
        tree-sitter-asciidoc
        tree-sitter-asciidoc_inline
        tree-sitter-astro
        tree-sitter-awk
        tree-sitter-bash
        tree-sitter-beancount
        tree-sitter-blade
        tree-sitter-caddy
        tree-sitter-caddyfile
        tree-sitter-clojure
        tree-sitter-cloudflare
        tree-sitter-comment
        tree-sitter-commonlisp
        tree-sitter-cpp
        tree-sitter-css
        tree-sitter-css_in_js
        tree-sitter-csv
        tree-sitter-cuda
        tree-sitter-cue
        tree-sitter-desktop
        tree-sitter-df
        tree-sitter-dhall
        tree-sitter-diff
        tree-sitter-dockerfile
        tree-sitter-dotenv
        tree-sitter-doxygen
        tree-sitter-dtd
        tree-sitter-ebnf
        tree-sitter-editorconfig
        tree-sitter-elisp
        tree-sitter-elm
        tree-sitter-elvish
        tree-sitter-embedded_template
        tree-sitter-eprime
        tree-sitter-faust
        tree-sitter-fennel
        tree-sitter-fish
        tree-sitter-gdscript
        tree-sitter-gherkin
        tree-sitter-ghostty
        tree-sitter-git_config
        tree-sitter-git_merge_conflict
        tree-sitter-git_rebase
        tree-sitter-gitattributes
        tree-sitter-gitcommit
        tree-sitter-gitignore
        tree-sitter-gleam
        tree-sitter-gnuplot
        tree-sitter-go
        tree-sitter-gomod
        tree-sitter-gpg
        tree-sitter-graphql
        tree-sitter-haskell
        tree-sitter-haskell_persistent
        tree-sitter-hcl
        tree-sitter-helm
        tree-sitter-hjson
        tree-sitter-hosts
        tree-sitter-html
        tree-sitter-htmldjango
        tree-sitter-htmljinja2
        tree-sitter-http
        tree-sitter-jack
        tree-sitter-java
        tree-sitter-javadoc
        tree-sitter-javascript
        tree-sitter-jjdescription
        tree-sitter-jq
        tree-sitter-jsdoc
        tree-sitter-json
        tree-sitter-json5
        tree-sitter-jsonc
        tree-sitter-jsonnet
        tree-sitter-julia
        tree-sitter-just
        tree-sitter-kanata
        tree-sitter-kanshi
        tree-sitter-kcl
        tree-sitter-kdl
        tree-sitter-kittyconf
        tree-sitter-kotlin
        tree-sitter-latex
        tree-sitter-ld
        tree-sitter-ledger
        tree-sitter-lilypond
        tree-sitter-lilypond_scheme
        tree-sitter-log
        tree-sitter-lua
        tree-sitter-luadoc
        tree-sitter-make
        tree-sitter-mandbconfig
        tree-sitter-markdoc
        tree-sitter-markdown
        tree-sitter-markdown_inline
        tree-sitter-mdx
        tree-sitter-mediawiki
        tree-sitter-meson
        tree-sitter-mustache
        tree-sitter-muttrc
        tree-sitter-navi
        tree-sitter-navi_stream
        tree-sitter-nginx
        tree-sitter-nickel
        tree-sitter-nix
        tree-sitter-nu
        tree-sitter-opencl
        tree-sitter-org
        tree-sitter-passwd
        tree-sitter-pem
        tree-sitter-perl
        tree-sitter-pest
        tree-sitter-php
        tree-sitter-php_only
        tree-sitter-phpdoc
        tree-sitter-powershell
        tree-sitter-printf
        tree-sitter-prisma
        tree-sitter-promql
        tree-sitter-properties
        tree-sitter-protobuf
        tree-sitter-purescript
        tree-sitter-pymanifest
        tree-sitter-python
        tree-sitter-readline
        tree-sitter-regex
        tree-sitter-robots
        tree-sitter-rst
        tree-sitter-rtf
        tree-sitter-ruby
        tree-sitter-rust
        tree-sitter-rust_format_args
        tree-sitter-rust_with_rstml
        tree-sitter-scheme
        tree-sitter-scss
        tree-sitter-sed
        tree-sitter-semver
        tree-sitter-snippet
        tree-sitter-sparql
        tree-sitter-spicedb
        tree-sitter-sql
        tree-sitter-sql_bigquery
        tree-sitter-ssh_client_config
        tree-sitter-ssh_config
        tree-sitter-strace
        tree-sitter-strings
        tree-sitter-styled
        tree-sitter-supercollider
        tree-sitter-svelte
        tree-sitter-sway
        tree-sitter-swift
        tree-sitter-terraform
        tree-sitter-tfvars
        tree-sitter-todome
        tree-sitter-todotxt
        tree-sitter-toml
        tree-sitter-tsv
        tree-sitter-tsx
        tree-sitter-twig
        tree-sitter-typescript
        tree-sitter-typst
        tree-sitter-udev
        tree-sitter-uri
        tree-sitter-uxntal
        tree-sitter-vala
        tree-sitter-vcard
        tree-sitter-vhs
        tree-sitter-vim
        tree-sitter-vimdoc
        tree-sitter-vue
        tree-sitter-xml
        tree-sitter-xresources
        tree-sitter-yaml
        tree-sitter-yarnlock
        tree-sitter-yasnippet
        tree-sitter-zathurarc
        tree-sitter-zig
      ];
    }
  );
}
