"$schema" = "https://starship.rs/config-schema.json"

[custom.git_branch_fallback]
command = "jj root >/dev/null 2>&1 || starship module git_branch"
description = "Display $git_branch if we're not in a jj repo"
when = true

[custom.jj]
detect_folders = [".jj"]
ignore_timeout = true
command = '''
  jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
    separate(" ",
      change_id.shortest(4),
      bookmarks,
      "|",
      concat(
        if(conflict, ""),
        if(divergent, ""),
        if(hidden, "󰘓"),
        if(immutable, ""),
      ),
      raw_escape_sequence("\x1b[1;32m") ++ if(empty, "(empty)"),
      raw_escape_sequence("\x1b[1;32m") ++ coalesce(
        truncate_end(72, description.first_line(), "…"),
        "(no description set)",
      ) ++ raw_escape_sequence("\x1b[0m"),
    )
  '
'''

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_metrics]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true
