brew 'aspell'
brew 'direnv'
brew 'git-delta' # magit-delta
brew 'ledger'
brew 'pandoc'

# https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/lookup/README.org#prerequisites
brew 'wordnet'
