# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  fish-done = {
    pname = "fish-done";
    version = "1.16.5";
    src = fetchFromGitHub ({
      owner = "franciscolourenco";
      repo = "done";
      rev = "1.16.5";
      fetchSubmodules = false;
      sha256 = "sha256-E0wveeDw1VzEH2kzn63q9hy1xkccfxQHBV2gVpu2IdQ=";
    });
  };
  fish-fzf = {
    pname = "fish-fzf";
    version = "v9.1";
    src = fetchFromGitHub ({
      owner = "PatrickF1";
      repo = "fzf.fish";
      rev = "v9.1";
      fetchSubmodules = false;
      sha256 = "sha256-OLmPtgUVX+/uiZg6lMl1xF4MHGVZUpTVota68coexWw=";
    });
  };
  fish-replay = {
    pname = "fish-replay";
    version = "1.2.1";
    src = fetchFromGitHub ({
      owner = "jorgebucaran";
      repo = "replay.fish";
      rev = "1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-bM6+oAd/HXaVgpJMut8bwqO54Le33hwO9qet9paK1kY=";
    });
  };
  fzf-scripts = {
    pname = "fzf-scripts";
    version = "7cf2925b0194f0ad116b84e8f45d8f01a87c774f";
    src = fetchgit {
      url = "https://github.com/DanielFGray/fzf-scripts";
      rev = "7cf2925b0194f0ad116b84e8f45d8f01a87c774f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-wGCbc9jF0kS2EKLIDPkR8kokE65wGDt+RptBeJvBrnc=";
    };
  };
  kitty-bortflower-icons = {
    pname = "kitty-bortflower-icons";
    version = "b19b3969d3bdc870beeff332355f92e38dc5a704";
    src = fetchgit {
      url = "https://github.com/DinkDonk/kitty-icon.git";
      rev = "b19b3969d3bdc870beeff332355f92e38dc5a704";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-3Jri8/y/s6/QkOBb03R9nd1gyZPGZlekhli9ShTzOxg=";
    };
  };
}
