# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  fish-abbr-tips = {
    pname = "fish-abbr-tips";
    version = "0.5.1";
    src = fetchFromGitHub ({
      owner = "gazorby";
      repo = "fish-abbreviation-tips";
      rev = "0.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-e6ooh8kKx1VTG2Qq1yXFqw7iwFiHx91ml1pIND/RufQ=";
    });
  };
  fish-done = {
    pname = "fish-done";
    version = "1.16.5";
    src = fetchFromGitHub ({
      owner = "franciscolourenco";
      repo = "done";
      rev = "1.16.5";
      fetchSubmodules = false;
      sha256 = "sha256-E0wveeDw1VzEH2kzn63q9hy1xkccfxQHBV2gVpu2IdQ=";
    });
  };
  fish-fzf = {
    pname = "fish-fzf";
    version = "v7.3";
    src = fetchFromGitHub ({
      owner = "PatrickF1";
      repo = "fzf.fish";
      rev = "v7.3";
      fetchSubmodules = false;
      sha256 = "sha256-qQ+mQQsPH9WvdgmLVoY6w+pYUyk062BKPxvKbr93rZo=";
    });
  };
  fish-nix-env = {
    pname = "fish-nix-env";
    version = "00c6cc762427efe08ac0bd0d1b1d12048d3ca727";
    src = fetchgit {
      url = "https://github.com/lilyball/nix-env.fish.git";
      rev = "00c6cc762427efe08ac0bd0d1b1d12048d3ca727";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-qt63SHfHWQnDBvaL+NOVgGA1Pt6tbWhV+1op0JoQNMM=";
    };
  };
  fish-nvm = {
    pname = "fish-nvm";
    version = "2.2.6";
    src = fetchFromGitHub ({
      owner = "jorgebucaran";
      repo = "nvm.fish";
      rev = "2.2.6";
      fetchSubmodules = false;
      sha256 = "sha256-KSL24EWsLaZhEc2Wmg9MEZaznAyIm2Rq1MbYLNntZZ8=";
    });
  };
  fish-tide = {
    pname = "fish-tide";
    version = "v5.0.1";
    src = fetchFromGitHub ({
      owner = "IlanCosman";
      repo = "tide";
      rev = "v5.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-EjEVyWwAtVqPFDEo9QUUAQXlAMlmEmaO0sqmjZSKI5M=";
    });
  };
  fish-z = {
    pname = "fish-z";
    version = "45a9ff6d0932b0e9835cbeb60b9794ba706eef10";
    src = fetchgit {
      url = "https://github.com/jethrokuan/z.git";
      rev = "45a9ff6d0932b0e9835cbeb60b9794ba706eef10";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-pWkEhjbcxXduyKz1mAFo90IuQdX7R8bLCQgb0R+hXs4=";
    };
  };
}
