# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  chemacs = {
    pname = "chemacs";
    version = "d53aa5e5e298a4244b70ae59e9d9ba34752c4bbb";
    src = fetchgit {
      url = "https://github.com/plexus/chemacs2.git";
      rev = "d53aa5e5e298a4244b70ae59e9d9ba34752c4bbb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-qR5+TeAe3Kvnn5YSj4utvfhC8gzCXswP2ZP6vI0FOgM=";
    };
  };
  fish-abbr-tips = {
    pname = "fish-abbr-tips";
    version = "0.5.1";
    src = fetchFromGitHub ({
      owner = "gazorby";
      repo = "fish-abbreviation-tips";
      rev = "0.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-e6ooh8kKx1VTG2Qq1yXFqw7iwFiHx91ml1pIND/RufQ=";
    });
  };
  fish-autopair = {
    pname = "fish-autopair";
    version = "1.0.3";
    src = fetchFromGitHub ({
      owner = "jorgebucaran";
      repo = "autopair.fish";
      rev = "1.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-l6WJ2kjDO/TnU9FSigjxk5xFp90xl68gDfggkE/wrlM=";
    });
  };
  fish-done = {
    pname = "fish-done";
    version = "1.16.5";
    src = fetchFromGitHub ({
      owner = "franciscolourenco";
      repo = "done";
      rev = "1.16.5";
      fetchSubmodules = false;
      sha256 = "sha256-E0wveeDw1VzEH2kzn63q9hy1xkccfxQHBV2gVpu2IdQ=";
    });
  };
  fish-fzf = {
    pname = "fish-fzf";
    version = "v8.3";
    src = fetchFromGitHub ({
      owner = "PatrickF1";
      repo = "fzf.fish";
      rev = "v8.3";
      fetchSubmodules = false;
      sha256 = "sha256-eSNUqvKXTxcuvICxo8BmVWL1ESXQuU7VhOl7aONrhwM=";
    });
  };
  fish-nix-env = {
    pname = "fish-nix-env";
    version = "7b65bd228429e852c8fdfa07601159130a818cfa";
    src = fetchgit {
      url = "https://github.com/lilyball/nix-env.fish.git";
      rev = "7b65bd228429e852c8fdfa07601159130a818cfa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-RG/0rfhgq6aEKNZ0XwIqOaZ6K5S4+/Y5EEMnIdtfPhk=";
    };
  };
  fish-nvm = {
    pname = "fish-nvm";
    version = "2.2.7";
    src = fetchFromGitHub ({
      owner = "jorgebucaran";
      repo = "nvm.fish";
      rev = "2.2.7";
      fetchSubmodules = false;
      sha256 = "sha256-VOai2SITr4d6y8jGc27FqQ8HBG8H70ctWmg8pF4EFeQ=";
    });
  };
  fish-replay = {
    pname = "fish-replay";
    version = "1.2.0";
    src = fetchFromGitHub ({
      owner = "jorgebucaran";
      repo = "replay.fish";
      rev = "1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-Q/9YVdiRSJw1SdcfQv2h7Lj6EyFustRk+kmh1eRRQ6k=";
    });
  };
  fish-z = {
    pname = "fish-z";
    version = "85f863f20f24faf675827fb00f3a4e15c7838d76";
    src = fetchgit {
      url = "https://github.com/jethrokuan/z.git";
      rev = "85f863f20f24faf675827fb00f3a4e15c7838d76";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-+FUBM7CodtZrYKqU542fQD+ZDGrd2438trKM0tIESs0=";
    };
  };
}
