# -*- mode: sh; eval: (sh-set-shell "zsh") -*-

[ -f "${0:a:h}/profile.zshenv" ] && source "${0:a:h}/profile.zshenv"

## Auto-generated by my nix config
[ -f "${0:a:h}/extra.zshenv" ] && source "${0:a:h}/extra.zshenv"

# If you have host-local configuration, this is where you'd put it
[ -f ~/.zshenv ] && source ~/.zshenv
