# -*- mode: sh; eval: (sh-set-shell "zsh") -*-

# Required, so no existence check -- failure is obvious immediately.
source "${ZDOTDIR}/profile.zshenv"

## Auto-generated by my nix config
[ -f "${ZDOTDIR}/extra.zshenv" ] && source "${ZDOTDIR}/extra.zshenv"

# If you have host-local configuration, this is where you'd put it
[ -f ~/.zshenv ] && source ~/.zshenv
