[kitty-bortflower-icons]
src.git = "https://github.com/DinkDonk/kitty-icon.git"
fetch.git = "https://github.com/DinkDonk/kitty-icon.git"

[firefox-lepton-ui]
src.git = "https://github.com/black7375/Firefox-UI-Fix"
fetch.git = "https://github.com/black7375/Firefox-UI-Fix"

[promnesia]
src.git = "https://github.com/karlicoss/promnesia"
fetch.git = "https://github.com/karlicoss/promnesia"

##: --- fish shell ---

[fish-autopair]
src.git = "https://github.com/jorgebucaran/autopair.fish"
fetch.git = "https://github.com/jorgebucaran/autopair.fish"

[fish-replay]
src.git = "https://github.com/jorgebucaran/replay.fish"
fetch.git = "https://github.com/jorgebucaran/replay.fish"

[fish-fifc]
src.git = "https://github.com/gazorby/fifc"
fetch.git = "https://github.com/gazorby/fifc"

[fzf-scripts]
src.git = "https://github.com/DanielFGray/fzf-scripts"
fetch.git = "https://github.com/DanielFGray/fzf-scripts"

[fish-nix-env]
src.git = "https://github.com/lilyball/nix-env.fish"
fetch.git = "https://github.com/lilyball/nix-env.fish"
