[kitty-bortflower-icons]
src.git = "https://github.com/DinkDonk/kitty-icon.git"
fetch.git = "https://github.com/DinkDonk/kitty-icon.git"

[firefox-lepton-ui]
src.git = "https://github.com/black7375/Firefox-UI-Fix"
fetch.git = "https://github.com/black7375/Firefox-UI-Fix"

[trellis-cli]
src.github = "roots/trellis-cli"
fetch.github = "roots/trellis-cli"

##: --- fish shell ---

[fish-autopair]
src.github = "jorgebucaran/autopair.fish"
fetch.github = "jorgebucaran/autopair.fish"

[fish-replay]
src.github = "jorgebucaran/replay.fish"
fetch.github = "jorgebucaran/replay.fish"

[fish-fifc]
src.git = "https://github.com/gazorby/fifc"
fetch.git = "https://github.com/gazorby/fifc"

[fzf-scripts]
src.git = "https://github.com/DanielFGray/fzf-scripts"
fetch.git = "https://github.com/DanielFGray/fzf-scripts"

[promnesia]
src.git = "https://github.com/karlicoss/promnesia"
# TODO: note that this might only return the latest tag
fetch.github = "karlicoss/promnesia"
