---
name: 'Flake checks'
"on":
  pull_request:
  push:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v33
        with:
          nix_conf: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = flakes nix-command pipe-operators
            keep-env-derivations = true
            keep-outputs = true
      - name: Setup binary cache
        uses: cachix/cachix-action@v14
        with:
          name: dotfield
          extraPullNames: dotfield,nix-community,nixpkgs-wayland,seadome
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: workflow/nix-shell-action@v3
        with:
          flakes-from-devshell: true
          script: nix-unit --flake .#tests
      - run: nix flake show -Lv
      - run: nix flake check -Lv
