name: 'Flake checks'

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      # Required for accessing private repos with an authorised key.
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Nix binary cache (Cachix)
        uses: cachix/cachix-action@master
        with:
          name: dotfield
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: dotfield,nix-community,nixpkgs-wayland

      - run: nix flake show -Lv
      - run: nix flake check -Lv
